---
repos:
  - hooks:
      - id: black
        stages: [commit]
        language_version: python3.10
        additional_dependencies: ['click==8.0.4']  # Why: https://github.com/psf/black/issues/2964
    repo: https://github.com/ambv/black
    rev: 21.7b0


  - hooks:
      - id: isort
        stages: [commit]
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4


  - repo: local
    hooks:
      - id: pytest
        stages: [manual]
        name: pytest
        entry: make tests
        language: system
        pass_filenames: false


  - repo: local
    hooks:
      - id: pylint
        stages: [commit]
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
              "--rcfile=pyproject.toml"
          ]
